local M = {}

M.config = {
  variant = nil,
  transparent = false,
  italic_comments = true,
  dim_inactive = false,
}

local function extend(base, extra)
  return vim.tbl_deep_extend("force", base, extra or {})
end

function M.setup(opts)
  M.config = extend(M.config, opts)
end

local function highlights(p, opts)
  local bg = opts.transparent and p.none or p.bg
  local side = opts.transparent and p.none or p.sidebar
  local comment = { fg = p.comment, italic = opts.italic_comments }

  return {
    -- Core editor
    Normal = { fg = p.fg, bg = bg },
    NormalNC = { fg = opts.dim_inactive and p.secondary or p.fg, bg = bg },
    NormalFloat = { fg = p.fg, bg = p.elevated },
    FloatBorder = { fg = p.border, bg = p.elevated },
    FloatTitle = { fg = p.cyan, bg = p.elevated, bold = true },
    ColorColumn = { bg = p.line },
    Conceal = { fg = p.muted },
    Cursor = { fg = p.bg, bg = p.accent },
    lCursor = { fg = p.bg, bg = p.accent },
    CursorIM = { fg = p.bg, bg = p.accent },
    CursorColumn = { bg = p.line },
    CursorLine = { bg = p.line },
    CursorLineNr = { fg = p.fg, bg = p.line, bold = true },
    LineNr = { fg = p.muted },
    LineNrAbove = { fg = p.muted },
    LineNrBelow = { fg = p.muted },
    Directory = { fg = p.blue },
    EndOfBuffer = { fg = bg },
    FoldColumn = { fg = p.muted, bg = side },
    Folded = { fg = p.secondary, bg = p.elevated },
    SignColumn = { fg = p.muted, bg = bg },
    CursorLineSign = { bg = p.line },
    MatchParen = { fg = p.accent, bg = p.selection, bold = true },
    ModeMsg = { fg = p.sage, bold = true },
    MoreMsg = { fg = p.sage },
    NonText = { fg = p.border },
    Pmenu = { fg = p.fg, bg = p.elevated },
    PmenuSel = { fg = p.fg, bg = p.selection },
    PmenuKind = { fg = p.cyan, bg = p.elevated },
    PmenuKindSel = { fg = p.cyan, bg = p.selection },
    PmenuExtra = { fg = p.muted, bg = p.elevated },
    PmenuExtraSel = { fg = p.secondary, bg = p.selection },
    PmenuSbar = { bg = p.panel },
    PmenuThumb = { bg = p.muted },
    Question = { fg = p.teal },
    QuickFixLine = { bg = p.selection },
    Search = { fg = p.bg, bg = p.amber },
    CurSearch = { fg = p.bg, bg = p.gold, bold = true },
    IncSearch = { fg = p.bg, bg = p.gold },
    Substitute = { fg = p.white, bg = p.red },
    SpecialKey = { fg = p.muted },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellLocal = { sp = p.teal, undercurl = true },
    SpellRare = { sp = p.violet, undercurl = true },
    StatusLine = { fg = p.fg, bg = p.elevated },
    StatusLineNC = { fg = p.muted, bg = p.panel },
    StatusLineTerm = { fg = p.fg, bg = p.elevated },
    StatusLineTermNC = { fg = p.muted, bg = p.panel },
    TabLine = { fg = p.muted, bg = p.panel },
    TabLineFill = { bg = p.panel },
    TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
    Title = { fg = p.blue, bold = true },
    Visual = { bg = p.selection },
    VisualNOS = { bg = p.selection_inactive },
    WarningMsg = { fg = p.amber },
    ErrorMsg = { fg = p.red },
    Whitespace = { fg = p.border },
    WildMenu = { fg = p.fg, bg = p.selection },
    WinBar = { fg = p.fg, bg = bg, bold = true },
    WinBarNC = { fg = p.muted, bg = bg },
    WinSeparator = { fg = p.border },

    -- Legacy syntax
    Comment = comment,
    Constant = { fg = p.gold },
    String = { fg = p.sage },
    Character = { fg = p.sage },
    Number = { fg = p.amber },
    Boolean = { fg = p.gold },
    Float = { fg = p.amber },
    Identifier = { fg = p.fg },
    Function = { fg = p.blue },
    Statement = { fg = p.violet },
    Conditional = { fg = p.violet },
    Repeat = { fg = p.violet },
    Label = { fg = p.gold },
    Operator = { fg = p.secondary },
    Keyword = { fg = p.violet },
    Exception = { fg = p.violet },
    PreProc = { fg = p.violet },
    Include = { fg = p.violet },
    Define = { fg = p.violet },
    Macro = { fg = p.violet },
    PreCondit = { fg = p.violet },
    Type = { fg = p.cyan },
    StorageClass = { fg = p.violet },
    Structure = { fg = p.cyan },
    Typedef = { fg = p.cyan },
    Special = { fg = p.teal },
    SpecialChar = { fg = p.amber },
    Tag = { fg = p.coral },
    Delimiter = { fg = p.secondary },
    SpecialComment = comment,
    Debug = { fg = p.coral },
    Underlined = { fg = p.cyan, underline = true },
    Ignore = { fg = p.muted },
    Error = { fg = p.red, undercurl = true, sp = p.red },
    Todo = { fg = p.bg, bg = p.amber, bold = true },

    -- Treesitter
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.violet },
    ["@variable.parameter"] = { fg = p.coral },
    ["@variable.parameter.builtin"] = { fg = p.coral },
    ["@variable.member"] = { fg = p.blue },
    ["@constant"] = { fg = p.gold },
    ["@constant.builtin"] = { fg = p.gold },
    ["@constant.macro"] = { fg = p.gold },
    ["@module"] = { fg = p.teal },
    ["@module.builtin"] = { fg = p.teal },
    ["@label"] = { fg = p.gold },
    ["@string"] = { fg = p.sage },
    ["@string.documentation"] = { fg = p.sage },
    ["@string.regexp"] = { fg = p.teal },
    ["@string.escape"] = { fg = p.amber },
    ["@string.special"] = { fg = p.amber },
    ["@character"] = { fg = p.sage },
    ["@character.special"] = { fg = p.amber },
    ["@boolean"] = { fg = p.gold },
    ["@number"] = { fg = p.amber },
    ["@number.float"] = { fg = p.amber },
    ["@type"] = { fg = p.cyan },
    ["@type.builtin"] = { fg = p.cyan },
    ["@type.definition"] = { fg = p.cyan },
    ["@attribute"] = { fg = p.gold },
    ["@property"] = { fg = p.blue },
    ["@function"] = { fg = p.blue },
    ["@function.builtin"] = { fg = p.blue },
    ["@function.call"] = { fg = p.blue },
    ["@function.macro"] = { fg = p.violet },
    ["@function.method"] = { fg = p.blue },
    ["@function.method.call"] = { fg = p.blue },
    ["@constructor"] = { fg = p.cyan },
    ["@operator"] = { fg = p.secondary },
    ["@keyword"] = { fg = p.violet },
    ["@keyword.coroutine"] = { fg = p.violet },
    ["@keyword.function"] = { fg = p.violet },
    ["@keyword.operator"] = { fg = p.violet },
    ["@keyword.import"] = { fg = p.violet },
    ["@keyword.type"] = { fg = p.violet },
    ["@keyword.modifier"] = { fg = p.violet },
    ["@keyword.repeat"] = { fg = p.violet },
    ["@keyword.return"] = { fg = p.violet },
    ["@keyword.debug"] = { fg = p.coral },
    ["@keyword.exception"] = { fg = p.violet },
    ["@keyword.conditional"] = { fg = p.violet },
    ["@keyword.conditional.ternary"] = { fg = p.violet },
    ["@keyword.directive"] = { fg = p.violet },
    ["@keyword.directive.define"] = { fg = p.violet },
    ["@punctuation.delimiter"] = { fg = p.secondary },
    ["@punctuation.bracket"] = { fg = p.secondary },
    ["@punctuation.special"] = { fg = p.amber },
    ["@comment"] = comment,
    ["@comment.documentation"] = comment,
    ["@comment.error"] = { fg = p.red, bold = true },
    ["@comment.warning"] = { fg = p.amber, bold = true },
    ["@comment.todo"] = { fg = p.bg, bg = p.amber, bold = true },
    ["@comment.note"] = { fg = p.bg, bg = p.blue, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = p.blue, bold = true },
    ["@markup.quote"] = comment,
    ["@markup.math"] = { fg = p.amber },
    ["@markup.link"] = { fg = p.cyan, underline = true },
    ["@markup.link.label"] = { fg = p.blue },
    ["@markup.link.url"] = { fg = p.teal, underline = true },
    ["@markup.raw"] = { fg = p.sage },
    ["@markup.list"] = { fg = p.coral },
    ["@markup.list.checked"] = { fg = p.sage },
    ["@markup.list.unchecked"] = { fg = p.muted },
    ["@diff.plus"] = { fg = p.sage },
    ["@diff.minus"] = { fg = p.red },
    ["@diff.delta"] = { fg = p.blue },
    ["@tag"] = { fg = p.coral },
    ["@tag.attribute"] = { fg = p.gold },
    ["@tag.delimiter"] = { fg = p.secondary },

    -- LSP semantic tokens
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.event"] = { fg = p.coral },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { fg = p.teal },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { fg = p.teal },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.mod.readonly"] = { fg = p.gold },
    ["@lsp.mod.deprecated"] = { fg = p.muted, strikethrough = true },
    ["@lsp.mod.documentation"] = { italic = opts.italic_comments },

    -- Diagnostics and messages
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.amber },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.teal },
    DiagnosticOk = { fg = p.sage },
    DiagnosticVirtualTextError = { fg = p.red, bg = p.diff_delete },
    DiagnosticVirtualTextWarn = { fg = p.amber, bg = p.line },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = p.diff_change },
    DiagnosticVirtualTextHint = { fg = p.teal, bg = p.line },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.teal, undercurl = true },
    DiagnosticDeprecated = { fg = p.muted, strikethrough = true },
    LspReferenceText = { bg = p.selection_inactive },
    LspReferenceRead = { bg = p.selection_inactive },
    LspReferenceWrite = { bg = p.selection },
    LspSignatureActiveParameter = { fg = p.coral, bg = p.selection, bold = true },

    -- Diff and version control
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { fg = p.red, bg = p.diff_delete },
    DiffText = { bg = p.diff_text, bold = true },
    GitSignsAdd = { fg = p.sage },
    GitSignsChange = { fg = p.blue },
    GitSignsDelete = { fg = p.red },
    GitSignsCurrentLineBlame = { fg = p.muted, italic = true },

    -- Common plugin groups
    TelescopeNormal = { fg = p.fg, bg = p.elevated },
    TelescopeBorder = { fg = p.border, bg = p.elevated },
    TelescopePromptNormal = { fg = p.fg, bg = p.panel },
    TelescopePromptBorder = { fg = p.border, bg = p.panel },
    TelescopePromptTitle = { fg = p.bg, bg = p.blue, bold = true },
    TelescopePreviewTitle = { fg = p.bg, bg = p.teal, bold = true },
    TelescopeResultsTitle = { fg = p.bg, bg = p.violet, bold = true },
    TelescopeSelection = { bg = p.selection },
    TelescopeMatching = { fg = p.cyan, bold = true },
    NeoTreeNormal = { fg = p.secondary, bg = side },
    NeoTreeNormalNC = { fg = p.secondary, bg = side },
    NeoTreeDirectoryName = { fg = p.blue },
    NeoTreeDirectoryIcon = { fg = p.blue },
    NeoTreeGitAdded = { fg = p.sage },
    NeoTreeGitModified = { fg = p.blue },
    NeoTreeGitDeleted = { fg = p.red },
    NvimTreeNormal = { fg = p.secondary, bg = side },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.cyan },
    NvimTreeGitNew = { fg = p.sage },
    NvimTreeGitDirty = { fg = p.blue },
    NvimTreeGitDeleted = { fg = p.red },
    WhichKey = { fg = p.cyan },
    WhichKeyGroup = { fg = p.blue },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.muted },
    WhichKeyFloat = { bg = p.elevated },
    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.cyan, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.cyan },
    CmpItemKindFunction = { fg = p.blue },
    CmpItemKindMethod = { fg = p.blue },
    CmpItemKindClass = { fg = p.cyan },
    CmpItemKindInterface = { fg = p.teal },
    CmpItemKindVariable = { fg = p.fg },
    CmpItemKindProperty = { fg = p.blue },
    CmpItemKindKeyword = { fg = p.violet },
    CmpItemKindText = { fg = p.secondary },
    CmpItemKindSnippet = { fg = p.amber },
    IndentBlanklineChar = { fg = p.border },
    IndentBlanklineContextChar = { fg = p.accent },
    IblIndent = { fg = p.border, nocombine = true },
    IblScope = { fg = p.accent, nocombine = true },
    LazyNormal = { fg = p.fg, bg = p.elevated },
    MasonNormal = { fg = p.fg, bg = p.elevated },
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder = { fg = p.amber },
    NotifyINFOBorder = { fg = p.blue },
    NotifyDEBUGBorder = { fg = p.muted },
    NotifyTRACEBorder = { fg = p.violet },
    NotifyERRORIcon = { fg = p.red },
    NotifyWARNIcon = { fg = p.amber },
    NotifyINFOIcon = { fg = p.blue },
    NotifyDEBUGIcon = { fg = p.muted },
    NotifyTRACEIcon = { fg = p.violet },
    DapBreakpoint = { fg = p.red },
    DapStopped = { fg = p.amber },
    DapLogPoint = { fg = p.blue },
  }
end

function M.load(variant, name)
  variant = variant or M.config.variant or (vim.o.background == "light" and "light" or "dark")
  if variant ~= "dark" and variant ~= "light" then
    error(("architect.nvim: invalid variant %q; expected 'dark' or 'light'"):format(variant))
  end

  vim.o.termguicolors = true
  vim.o.background = variant
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = name or "architect"
  local palettes = require("architect.palette")
  local p = palettes[variant]

  for group, spec in pairs(highlights(p, M.config)) do
    vim.api.nvim_set_hl(0, group, spec)
  end

  for index, color in ipairs(palettes.terminal[variant]) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end
end

return M
