import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const modes = {
  dark: {
    type: "dark",
    name: "Architect Dark",
    p: {
      bg: "#171A1F", side: "#1B1F26", activity: "#16191E", panel: "#191D23",
      elevated: "#20252D", line: "#20252C", selection: "#344256", selectionInactive: "#2A3545",
      fg: "#D8DEE9", secondary: "#A7B0BF", muted: "#8792A3", comment: "#899696",
      border: "#2B313B", accent: "#88C0D0", violet: "#B48EAD", blue: "#81A1C1",
      cyan: "#88C0D0", sage: "#A3BE8C", amber: "#D9B26F", gold: "#E0C58F",
      coral: "#D08770", red: "#BF6B73", teal: "#7FB4A8", white: "#ECEFF4",
      shadow: "#0D0F1266", overlay: "#FFFFFF0B", hover: "#FFFFFF0D"
    },
    ansi: {
      black: "#3B4252", red: "#BF6B73", green: "#91AD7D", yellow: "#C9A55F",
      blue: "#7797B7", magenta: "#A681A0", cyan: "#72A79D", white: "#C7CED9",
      brightBlack: "#667080", brightRed: "#D27C83", brightGreen: "#A3BE8C",
      brightYellow: "#D9B26F", brightBlue: "#8AAAC8", brightMagenta: "#B994B1",
      brightCyan: "#88C0D0", brightWhite: "#ECEFF4"
    }
  },
  light: {
    type: "light",
    name: "Architect Light",
    p: {
      bg: "#F4F5F2", side: "#ECEFEB", activity: "#E7EAE8", panel: "#EFF1EE",
      elevated: "#E4E8E6", line: "#E9ECEA", selection: "#CDD8E3", selectionInactive: "#DEE4E8",
      fg: "#2E3440", secondary: "#4C566A", muted: "#6D788B", comment: "#68746D",
      border: "#D5DAD7", accent: "#4C7A91", violet: "#76558F", blue: "#3E6F91",
      cyan: "#357A83", sage: "#547A50", amber: "#9A6B2F", gold: "#80672F",
      coral: "#9C5E4D", red: "#A24E57", teal: "#417A70", white: "#FFFFFF",
      shadow: "#45505B24", overlay: "#2E34400A", hover: "#2E34400D"
    },
    ansi: {
      black: "#3C4350", red: "#A24E57", green: "#547A50", yellow: "#886525",
      blue: "#3E6F91", magenta: "#76558F", cyan: "#417A70", white: "#D7DAD7",
      brightBlack: "#6D788B", brightRed: "#B76068", brightGreen: "#668D61",
      brightYellow: "#9A7633", brightBlue: "#527F9D", brightMagenta: "#87689D",
      brightCyan: "#538B82", brightWhite: "#FDFEFC"
    }
  }
};

const alpha = (hex, opacity) => `${hex}${opacity}`;

function workbench(p, ansi) {
  const c = {
    "focusBorder": alpha(p.accent, "80"),
    "foreground": p.fg,
    "disabledForeground": alpha(p.muted, "99"),
    "descriptionForeground": p.secondary,
    "errorForeground": p.red,
    "icon.foreground": p.secondary,
    "sash.hoverBorder": alpha(p.accent, "99"),
    "window.activeBorder": p.border,
    "window.inactiveBorder": alpha(p.border, "99"),
    "textBlockQuote.background": p.overlay,
    "textBlockQuote.border": p.teal,
    "textCodeBlock.background": p.elevated,
    "textLink.foreground": p.blue,
    "textLink.activeForeground": p.cyan,
    "textPreformat.foreground": p.gold,
    "button.background": p.blue,
    "button.foreground": p.white,
    "button.hoverBackground": p.cyan,
    "button.secondaryBackground": p.elevated,
    "button.secondaryForeground": p.fg,
    "button.secondaryHoverBackground": p.selection,
    "checkbox.background": p.elevated,
    "checkbox.foreground": p.accent,
    "checkbox.border": p.border,
    "dropdown.background": p.elevated,
    "dropdown.foreground": p.fg,
    "dropdown.border": p.border,
    "input.background": p.elevated,
    "input.foreground": p.fg,
    "input.border": p.border,
    "input.placeholderForeground": p.muted,
    "inputOption.activeBackground": alpha(p.accent, "25"),
    "inputOption.activeBorder": alpha(p.accent, "80"),
    "inputValidation.errorBackground": alpha(p.red, "1F"),
    "inputValidation.errorBorder": p.red,
    "inputValidation.warningBackground": alpha(p.amber, "1F"),
    "inputValidation.warningBorder": p.amber,
    "inputValidation.infoBackground": alpha(p.blue, "1F"),
    "inputValidation.infoBorder": p.blue,
    "scrollbar.shadow": p.shadow,
    "scrollbarSlider.background": alpha(p.muted, "33"),
    "scrollbarSlider.hoverBackground": alpha(p.muted, "55"),
    "scrollbarSlider.activeBackground": alpha(p.accent, "66"),
    "badge.background": p.selection,
    "badge.foreground": p.fg,
    "progressBar.background": p.accent,
    "list.activeSelectionBackground": p.selection,
    "list.activeSelectionForeground": p.fg,
    "list.inactiveSelectionBackground": p.selectionInactive,
    "list.inactiveSelectionForeground": p.fg,
    "list.hoverBackground": p.hover,
    "list.hoverForeground": p.fg,
    "list.focusBackground": p.selectionInactive,
    "list.focusForeground": p.fg,
    "list.highlightForeground": p.blue,
    "list.invalidItemForeground": p.red,
    "list.errorForeground": p.red,
    "list.warningForeground": p.amber,
    "listFilterWidget.background": p.elevated,
    "listFilterWidget.outline": p.border,
    "listFilterWidget.noMatchesOutline": p.red,
    "tree.indentGuidesStroke": p.border,
    "tree.inactiveIndentGuidesStroke": alpha(p.border, "99"),
    "activityBar.background": p.activity,
    "activityBar.foreground": p.fg,
    "activityBar.inactiveForeground": p.muted,
    "activityBar.border": p.border,
    "activityBar.activeBorder": p.accent,
    "activityBar.activeBackground": p.overlay,
    "activityBarBadge.background": p.accent,
    "activityBarBadge.foreground": p.activity,
    "activityBarTop.foreground": p.fg,
    "activityBarTop.inactiveForeground": p.muted,
    "sideBar.background": p.side,
    "sideBar.foreground": p.secondary,
    "sideBar.border": p.border,
    "sideBarTitle.foreground": p.fg,
    "sideBarSectionHeader.background": p.elevated,
    "sideBarSectionHeader.foreground": p.fg,
    "sideBarSectionHeader.border": p.border,
    "sideBarActivityBarTop.border": p.border,
    "minimap.findMatchHighlight": alpha(p.amber, "99"),
    "minimap.selectionHighlight": alpha(p.blue, "66"),
    "minimap.errorHighlight": p.red,
    "minimap.warningHighlight": p.amber,
    "minimap.background": p.bg,
    "minimapSlider.background": alpha(p.muted, "22"),
    "minimapSlider.hoverBackground": alpha(p.muted, "3D"),
    "minimapSlider.activeBackground": alpha(p.accent, "55"),
    "editorGroup.border": p.border,
    "editorGroup.dropBackground": alpha(p.blue, "22"),
    "editorGroupHeader.tabsBackground": p.panel,
    "editorGroupHeader.tabsBorder": p.border,
    "editorGroupHeader.noTabsBackground": p.bg,
    "tab.activeBackground": p.bg,
    "tab.activeForeground": p.fg,
    "tab.activeBorderTop": p.accent,
    "tab.activeBorder": "#00000000",
    "tab.inactiveBackground": p.panel,
    "tab.inactiveForeground": p.muted,
    "tab.hoverBackground": p.elevated,
    "tab.hoverForeground": p.fg,
    "tab.border": p.border,
    "tab.unfocusedActiveForeground": p.secondary,
    "tab.unfocusedInactiveForeground": p.muted,
    "tab.lastPinnedBorder": p.border,
    "editor.background": p.bg,
    "editor.foreground": p.fg,
    "editorLineNumber.foreground": p.muted,
    "editorLineNumber.activeForeground": p.fg,
    "editorCursor.foreground": p.accent,
    "editor.selectionBackground": p.selection,
    "editor.selectionForeground": p.fg,
    "editor.inactiveSelectionBackground": p.selectionInactive,
    "editor.selectionHighlightBackground": alpha(p.blue, "26"),
    "editor.wordHighlightBackground": alpha(p.blue, "24"),
    "editor.wordHighlightStrongBackground": alpha(p.violet, "28"),
    "editor.wordHighlightTextBackground": alpha(p.teal, "20"),
    "editor.findMatchBackground": alpha(p.amber, "59"),
    "editor.findMatchBorder": alpha(p.amber, "B3"),
    "editor.findMatchHighlightBackground": alpha(p.amber, "2E"),
    "editor.findRangeHighlightBackground": alpha(p.blue, "18"),
    "editor.hoverHighlightBackground": alpha(p.blue, "20"),
    "editor.lineHighlightBackground": p.line,
    "editor.lineHighlightBorder": "#00000000",
    "editor.rangeHighlightBackground": alpha(p.blue, "18"),
    "editor.symbolHighlightBackground": alpha(p.teal, "22"),
    "editorWhitespace.foreground": alpha(p.muted, "55"),
    "editorIndentGuide.background1": p.border,
    "editorIndentGuide.activeBackground1": alpha(p.accent, "80"),
    "editorRuler.foreground": p.border,
    "editorCodeLens.foreground": p.muted,
    "editorLink.activeForeground": p.cyan,
    "editorLightBulb.foreground": p.amber,
    "editorLightBulbAutoFix.foreground": p.teal,
    "editorBracketMatch.background": alpha(p.accent, "26"),
    "editorBracketMatch.border": alpha(p.accent, "99"),
    "editorBracketHighlight.foreground1": p.blue,
    "editorBracketHighlight.foreground2": p.violet,
    "editorBracketHighlight.foreground3": p.teal,
    "editorBracketHighlight.foreground4": p.amber,
    "editorBracketHighlight.foreground5": p.sage,
    "editorBracketHighlight.foreground6": p.secondary,
    "editorBracketHighlight.unexpectedBracket.foreground": p.red,
    "editorBracketPairGuide.background1": alpha(p.blue, "4D"),
    "editorBracketPairGuide.background2": alpha(p.violet, "4D"),
    "editorBracketPairGuide.background3": alpha(p.teal, "4D"),
    "editorBracketPairGuide.background4": alpha(p.amber, "4D"),
    "editorBracketPairGuide.background5": alpha(p.sage, "4D"),
    "editorBracketPairGuide.background6": alpha(p.secondary, "4D"),
    "editorBracketPairGuide.activeBackground1": p.blue,
    "editorBracketPairGuide.activeBackground2": p.violet,
    "editorBracketPairGuide.activeBackground3": p.teal,
    "editorBracketPairGuide.activeBackground4": p.amber,
    "editorBracketPairGuide.activeBackground5": p.sage,
    "editorBracketPairGuide.activeBackground6": p.secondary,
    "editorGutter.background": p.bg,
    "editorGutter.modifiedBackground": p.blue,
    "editorGutter.addedBackground": p.sage,
    "editorGutter.deletedBackground": p.red,
    "editorGutter.foldingControlForeground": p.muted,
    "editorError.foreground": p.red,
    "editorError.border": "#00000000",
    "editorWarning.foreground": p.amber,
    "editorWarning.border": "#00000000",
    "editorInfo.foreground": p.blue,
    "editorInfo.border": "#00000000",
    "editorHint.foreground": p.teal,
    "editorHint.border": "#00000000",
    "editorUnnecessaryCode.opacity": "#00000088",
    "editorUnnecessaryCode.border": "#00000000",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": alpha(p.red, "CC"),
    "editorOverviewRuler.warningForeground": alpha(p.amber, "CC"),
    "editorOverviewRuler.infoForeground": alpha(p.blue, "CC"),
    "editorOverviewRuler.addedForeground": alpha(p.sage, "B3"),
    "editorOverviewRuler.modifiedForeground": alpha(p.blue, "B3"),
    "editorOverviewRuler.deletedForeground": alpha(p.red, "B3"),
    "editorWidget.background": p.elevated,
    "editorWidget.foreground": p.fg,
    "editorWidget.border": p.border,
    "editorWidget.resizeBorder": p.accent,
    "editorSuggestWidget.background": p.elevated,
    "editorSuggestWidget.border": p.border,
    "editorSuggestWidget.foreground": p.fg,
    "editorSuggestWidget.highlightForeground": p.cyan,
    "editorSuggestWidget.selectedBackground": p.selection,
    "editorSuggestWidget.selectedForeground": p.fg,
    "editorHoverWidget.background": p.elevated,
    "editorHoverWidget.foreground": p.fg,
    "editorHoverWidget.border": p.border,
    "editorHoverWidget.highlightForeground": p.cyan,
    "editorHoverWidget.statusBarBackground": p.panel,
    "editorGhostText.foreground": p.muted,
    "editorInlayHint.background": alpha(p.blue, "18"),
    "editorInlayHint.foreground": p.muted,
    "editorInlayHint.typeBackground": alpha(p.teal, "18"),
    "editorInlayHint.typeForeground": p.teal,
    "editorInlayHint.parameterBackground": alpha(p.amber, "18"),
    "editorInlayHint.parameterForeground": p.gold,
    "editorStickyScroll.background": p.bg,
    "editorStickyScroll.border": p.border,
    "editorStickyScrollHover.background": p.line,
    "peekView.border": p.accent,
    "peekViewEditor.background": p.panel,
    "peekViewEditor.matchHighlightBackground": alpha(p.amber, "4D"),
    "peekViewResult.background": p.side,
    "peekViewResult.fileForeground": p.fg,
    "peekViewResult.lineForeground": p.secondary,
    "peekViewResult.matchHighlightBackground": alpha(p.amber, "38"),
    "peekViewResult.selectionBackground": p.selection,
    "peekViewResult.selectionForeground": p.fg,
    "peekViewTitle.background": p.elevated,
    "peekViewTitleDescription.foreground": p.muted,
    "peekViewTitleLabel.foreground": p.fg,
    "diffEditor.insertedTextBackground": alpha(p.sage, "24"),
    "diffEditor.removedTextBackground": alpha(p.red, "24"),
    "diffEditor.insertedLineBackground": alpha(p.sage, "12"),
    "diffEditor.removedLineBackground": alpha(p.red, "12"),
    "diffEditor.diagonalFill": alpha(p.muted, "26"),
    "diffEditorGutter.insertedLineBackground": alpha(p.sage, "28"),
    "diffEditorGutter.removedLineBackground": alpha(p.red, "28"),
    "diffEditorOverview.insertedForeground": p.sage,
    "diffEditorOverview.removedForeground": p.red,
    "merge.currentHeaderBackground": alpha(p.blue, "33"),
    "merge.currentContentBackground": alpha(p.blue, "17"),
    "merge.incomingHeaderBackground": alpha(p.teal, "33"),
    "merge.incomingContentBackground": alpha(p.teal, "17"),
    "merge.commonHeaderBackground": alpha(p.muted, "2B"),
    "merge.commonContentBackground": alpha(p.muted, "15"),
    "mergeEditor.change.background": alpha(p.amber, "1F"),
    "mergeEditor.change.word.background": alpha(p.amber, "3D"),
    "mergeEditor.conflict.unhandledUnfocused.border": p.coral,
    "mergeEditor.conflict.unhandledFocused.border": p.amber,
    "mergeEditor.conflict.handledUnfocused.border": p.border,
    "mergeEditor.conflict.handledFocused.border": p.teal,
    "panel.background": p.panel,
    "panel.border": p.border,
    "panelTitle.activeForeground": p.fg,
    "panelTitle.inactiveForeground": p.muted,
    "panelTitle.activeBorder": p.accent,
    "panelInput.border": p.border,
    "panelSection.border": p.border,
    "panelSectionHeader.background": p.elevated,
    "panelSectionHeader.foreground": p.fg,
    "statusBar.background": p.elevated,
    "statusBar.foreground": p.secondary,
    "statusBar.border": p.border,
    "statusBar.debuggingBackground": p.coral,
    "statusBar.debuggingForeground": p.white,
    "statusBar.noFolderBackground": p.side,
    "statusBar.noFolderForeground": p.secondary,
    "statusBarItem.activeBackground": alpha(p.accent, "24"),
    "statusBarItem.hoverBackground": p.hover,
    "statusBarItem.prominentBackground": p.selection,
    "statusBarItem.prominentForeground": p.fg,
    "statusBarItem.errorBackground": p.red,
    "statusBarItem.errorForeground": p.white,
    "statusBarItem.warningBackground": p.amber,
    "statusBarItem.warningForeground": p.activity,
    "titleBar.activeBackground": p.activity,
    "titleBar.activeForeground": p.fg,
    "titleBar.inactiveBackground": p.panel,
    "titleBar.inactiveForeground": p.muted,
    "titleBar.border": p.border,
    "commandCenter.background": p.elevated,
    "commandCenter.foreground": p.secondary,
    "commandCenter.border": p.border,
    "commandCenter.activeBackground": p.selection,
    "commandCenter.activeForeground": p.fg,
    "commandCenter.inactiveForeground": p.muted,
    "quickInput.background": p.elevated,
    "quickInput.foreground": p.fg,
    "quickInputList.focusBackground": p.selection,
    "quickInputList.focusForeground": p.fg,
    "quickInputList.focusIconForeground": p.accent,
    "pickerGroup.border": p.border,
    "pickerGroup.foreground": p.cyan,
    "menu.background": p.elevated,
    "menu.foreground": p.fg,
    "menu.selectionBackground": p.selection,
    "menu.selectionForeground": p.fg,
    "menu.separatorBackground": p.border,
    "menu.border": p.border,
    "menubar.selectionBackground": p.hover,
    "menubar.selectionForeground": p.fg,
    "menubar.selectionBorder": "#00000000",
    "notificationCenter.border": p.border,
    "notificationCenterHeader.background": p.panel,
    "notificationCenterHeader.foreground": p.fg,
    "notificationToast.border": p.border,
    "notifications.background": p.elevated,
    "notifications.foreground": p.fg,
    "notifications.border": p.border,
    "notificationLink.foreground": p.cyan,
    "notificationsErrorIcon.foreground": p.red,
    "notificationsWarningIcon.foreground": p.amber,
    "notificationsInfoIcon.foreground": p.blue,
    "breadcrumb.background": p.bg,
    "breadcrumb.foreground": p.muted,
    "breadcrumb.focusForeground": p.fg,
    "breadcrumb.activeSelectionForeground": p.fg,
    "breadcrumbPicker.background": p.elevated,
    "gitDecoration.addedResourceForeground": p.sage,
    "gitDecoration.modifiedResourceForeground": p.blue,
    "gitDecoration.deletedResourceForeground": p.red,
    "gitDecoration.renamedResourceForeground": p.teal,
    "gitDecoration.untrackedResourceForeground": p.sage,
    "gitDecoration.ignoredResourceForeground": p.muted,
    "gitDecoration.conflictingResourceForeground": p.coral,
    "gitDecoration.submoduleResourceForeground": p.violet,
    "testing.iconPassed": p.sage,
    "testing.iconFailed": p.red,
    "testing.iconErrored": p.coral,
    "testing.iconQueued": p.muted,
    "testing.iconUnset": p.muted,
    "testing.iconSkipped": p.gold,
    "testing.runAction": p.teal,
    "testing.peekBorder": p.red,
    "testing.message.error.decorationForeground": p.red,
    "testing.message.info.decorationForeground": p.blue,
    "debugIcon.breakpointForeground": p.red,
    "debugIcon.breakpointDisabledForeground": p.muted,
    "debugIcon.startForeground": p.sage,
    "debugIcon.pauseForeground": p.blue,
    "debugIcon.stopForeground": p.red,
    "debugIcon.disconnectForeground": p.coral,
    "debugIcon.restartForeground": p.teal,
    "debugIcon.stepOverForeground": p.blue,
    "debugIcon.stepIntoForeground": p.cyan,
    "debugIcon.stepOutForeground": p.violet,
    "debugIcon.continueForeground": p.sage,
    "debugToolBar.background": p.elevated,
    "debugToolBar.border": p.border,
    "debugExceptionWidget.background": p.elevated,
    "debugExceptionWidget.border": p.red,
    "terminal.background": p.panel,
    "terminal.foreground": p.fg,
    "terminalCursor.background": p.panel,
    "terminalCursor.foreground": p.accent,
    "terminal.selectionBackground": p.selection,
    "terminal.inactiveSelectionBackground": p.selectionInactive,
    "terminal.border": p.border,
    "terminal.dropBackground": alpha(p.blue, "22"),
    "terminalCommandDecoration.defaultBackground": p.muted,
    "terminalCommandDecoration.successBackground": p.sage,
    "terminalCommandDecoration.errorBackground": p.red,
    "terminalOverviewRuler.cursorForeground": p.accent,
    "terminalOverviewRuler.findMatchForeground": p.amber,
    "terminal.ansiBlack": ansi.black,
    "terminal.ansiRed": ansi.red,
    "terminal.ansiGreen": ansi.green,
    "terminal.ansiYellow": ansi.yellow,
    "terminal.ansiBlue": ansi.blue,
    "terminal.ansiMagenta": ansi.magenta,
    "terminal.ansiCyan": ansi.cyan,
    "terminal.ansiWhite": ansi.white,
    "terminal.ansiBrightBlack": ansi.brightBlack,
    "terminal.ansiBrightRed": ansi.brightRed,
    "terminal.ansiBrightGreen": ansi.brightGreen,
    "terminal.ansiBrightYellow": ansi.brightYellow,
    "terminal.ansiBrightBlue": ansi.brightBlue,
    "terminal.ansiBrightMagenta": ansi.brightMagenta,
    "terminal.ansiBrightCyan": ansi.brightCyan,
    "terminal.ansiBrightWhite": ansi.brightWhite,
    "markdown.extension.editor.codeSpan.backgroundColor": p.elevated,
    "markdown.extension.editor.codeSpan.borderColor": p.border,
    "markdown.extension.editor.formattingMark.foreground": p.muted,
    "walkThrough.embeddedEditorBackground": p.panel,
    "welcomePage.background": p.bg,
    "welcomePage.tileBackground": p.elevated,
    "welcomePage.tileHoverBackground": p.selection,
    "settings.headerForeground": p.fg,
    "settings.modifiedItemIndicator": p.accent,
    "settings.dropdownBackground": p.elevated,
    "settings.dropdownForeground": p.fg,
    "settings.dropdownBorder": p.border,
    "settings.textInputBackground": p.elevated,
    "settings.textInputForeground": p.fg,
    "settings.textInputBorder": p.border
  };
  return c;
}

const rule = (name, scope, foreground, fontStyle) => ({
  name,
  scope: Array.isArray(scope) ? scope : scope.split(", "),
  settings: { foreground, ...(fontStyle ? { fontStyle } : {}) }
});

function tokenColors(p) {
  return [
    rule("Comments", "comment, punctuation.definition.comment", p.comment, "italic"),
    rule("Documentation comments", "comment.block.documentation, string.quoted.docstring, comment.line.documentation", p.comment, "italic"),
    rule("Keywords", "keyword, storage.type, storage.modifier", p.violet),
    rule("Control flow", "keyword.control, keyword.control.flow, keyword.control.conditional, keyword.control.loop", p.violet),
    rule("Operators", "keyword.operator, keyword.operator.assignment, keyword.operator.comparison, keyword.operator.logical", p.secondary),
    rule("Punctuation", "punctuation, meta.brace, meta.delimiter, punctuation.separator, punctuation.terminator", p.secondary),
    rule("Variables", "variable, meta.definition.variable.name", p.fg),
    rule("Language variables", "variable.language, variable.language.this, variable.language.self", p.violet),
    rule("Constants", "variable.other.constant, constant.other, support.constant", p.gold),
    rule("Parameters", "variable.parameter, meta.parameters variable", p.coral),
    rule("Properties", "variable.other.property, support.type.property-name, meta.object-literal.key", p.blue),
    rule("Functions", "entity.name.function, support.function, meta.function-call entity.name.function", p.blue),
    rule("Methods", "entity.name.function.member, meta.method-call entity.name.function, variable.function", p.blue),
    rule("Constructors", "entity.name.function.constructor, support.class", p.cyan),
    rule("Classes and structs", "entity.name.type.class, entity.name.type.struct, support.class, support.type", p.cyan),
    rule("Interfaces and traits", "entity.name.type.interface, entity.name.type.trait", p.teal),
    rule("Enums", "entity.name.type.enum", p.cyan),
    rule("Enum members", "variable.other.enummember, constant.other.enum", p.gold),
    rule("Types", "entity.name.type, storage.type.numeric, storage.type.primitive", p.cyan),
    rule("Type parameters", "entity.name.type.parameter, meta.type.parameters entity.name.type", p.teal),
    rule("Namespaces and modules", "entity.name.namespace, entity.name.type.module, support.module", p.teal),
    rule("Strings", "string, punctuation.definition.string", p.sage),
    rule("Template punctuation", "punctuation.definition.template-expression, punctuation.section.embedded", p.amber),
    rule("Escape sequences", "constant.character.escape, constant.character.format.placeholder", p.amber),
    rule("Numbers", "constant.numeric", p.amber),
    rule("Booleans", "constant.language.boolean", p.gold),
    rule("Null and nil", "constant.language.null, constant.language.nil, constant.language.undefined", p.gold),
    rule("Regular expressions", "string.regexp, constant.regexp, keyword.control.anchor.regexp", p.teal),
    rule("Tags", "entity.name.tag, punctuation.definition.tag", p.coral),
    rule("Attributes", "entity.other.attribute-name, meta.attribute", p.gold),
    rule("CSS selectors", "entity.other.attribute-name.class.css, entity.other.attribute-name.id.css, entity.name.tag.css", p.coral),
    rule("CSS properties", "support.type.property-name.css, meta.property-name.css", p.blue),
    rule("CSS values and units", "support.constant.property-value.css, constant.numeric.css, keyword.other.unit", p.amber),
    rule("JSON keys", "support.type.property-name.json, string.json meta.structure.dictionary.value", p.blue),
    rule("YAML keys", "entity.name.tag.yaml, string.unquoted.plain.out.yaml", p.blue),
    rule("Shell commands", "support.function.builtin.shell, entity.name.function.shell, meta.function-call.shell", p.blue),
    rule("Shell variables", "variable.other.normal.shell, variable.other.positional.shell", p.coral),
    rule("Markdown headings", "markup.heading, entity.name.section.markdown, punctuation.definition.heading.markdown", p.blue, "bold"),
    rule("Markdown links", "markup.underline.link, string.other.link.title.markdown, meta.link.inline.markdown", p.cyan),
    rule("Markdown inline code", "markup.inline.raw, markup.raw.inline", p.teal),
    rule("Markdown code blocks", "markup.fenced_code.block, markup.raw.block", p.sage),
    rule("Markdown blockquotes", "markup.quote, punctuation.definition.quote.begin.markdown", p.comment, "italic"),
    rule("Markdown bold", "markup.bold", p.fg, "bold"),
    rule("Markdown italic", "markup.italic", p.fg, "italic"),
    rule("Diff inserted", "markup.inserted, meta.diff.header.to-file", p.sage),
    rule("Diff deleted", "markup.deleted, meta.diff.header.from-file", p.red),
    rule("Diff changed", "markup.changed", p.amber),
    rule("Invalid", "invalid, invalid.illegal", p.red, "underline"),
    rule("Deprecated", "invalid.deprecated, entity.name.function.deprecated", p.muted, "strikethrough")
  ];
}

function semanticTokenColors(p) {
  return {
    "namespace": p.teal,
    "type": p.cyan,
    "type.defaultLibrary": p.cyan,
    "class": p.cyan,
    "class.defaultLibrary": p.cyan,
    "enum": p.cyan,
    "interface": p.teal,
    "struct": p.cyan,
    "typeParameter": p.teal,
    "parameter": p.coral,
    "variable": p.fg,
    "variable.readonly": p.gold,
    "variable.defaultLibrary": p.violet,
    "property": p.blue,
    "property.readonly": p.gold,
    "enumMember": p.gold,
    "decorator": p.gold,
    "event": p.coral,
    "function": p.blue,
    "function.defaultLibrary": p.blue,
    "method": p.blue,
    "macro": p.violet,
    "label": p.gold,
    "comment": { foreground: p.comment, italic: true },
    "string": p.sage,
    "number": p.amber,
    "regexp": p.teal,
    "operator": p.secondary,
    "keyword": p.violet,
    "modifier": p.violet,
    "*.declaration": { bold: false },
    "*.deprecated": { foreground: p.muted, strikethrough: true },
    "*.documentation": { italic: true }
  };
}

function makeTheme(mode) {
  const { p, ansi, type, name } = mode;
  return {
    "$schema": "vscode://schemas/color-theme",
    "name": name,
    "type": type,
    "semanticHighlighting": true,
    "colors": workbench(p, ansi),
    "tokenColors": tokenColors(p),
    "semanticTokenColors": semanticTokenColors(p)
  };
}

await mkdir(path.join(root, "themes"), { recursive: true });
for (const [key, mode] of Object.entries(modes)) {
  const file = path.join(root, "themes", `architect-${key}-color-theme.json`);
  await writeFile(file, `${JSON.stringify(makeTheme(mode), null, 2)}\n`);
}

console.log("Generated Architect Light and Architect Dark theme files.");
